const vocabulario = {
  "Lección 1": [
    { jp: "わたし", romaji: "watashi", es: "yo" },
    { jp: "わたしたち", romaji: "watashitachi", es: "nosotros" },
    { jp: "あなた", romaji: "anata", es: "usted" },
    { jp: "あのひと", romaji: "ano hito", es: "aquella persona, él, ella" },
    { jp: "あのかた", romaji: "ano kata", es: "forma cortés de あのひと" },
    { jp: "みなさん", romaji: "minasan", es: "señoras y señores, todos ustedes" },
    { jp: "〜さん", romaji: "〜san", es: "Sr., Sra., Srta. (sufijo de respeto)" },
    { jp: "〜ちゃん", romaji: "〜chan", es: "sufijo familiar (niños, afecto)" },
    { jp: "〜くん", romaji: "〜kun", es: "sufijo para niños varones" },
    { jp: "〜じん", romaji: "〜jin", es: "sufijo para nacionalidad, ej. アメリカじん estadounidense" },
    { jp: "せんせい", romaji: "sensei", es: "maestro, profesor, instructor (no para uno mismo)" },
    { jp: "きょうし", romaji: "kyoushi", es: "maestro (para referirse a sí mismo)" },
    { jp: "がくせい", romaji: "gakusei", es: "estudiante" },
    { jp: "かいしゃいん", romaji: "kaishain", es: "empleado de empresa" },
    { jp: "しゃいん", romaji: "shain", es: "empleado (usado con nombre de empresa)" },
    { jp: "ぎんこういん", romaji: "ginkouin", es: "empleado de banco" },
    { jp: "いしゃ", romaji: "isha", es: "médico" },
    { jp: "けんきゅうしゃ", romaji: "kenkyuusha", es: "investigador, estudioso" },
    { jp: "エンジニア", romaji: "enjinia", es: "ingeniero" },
    { jp: "だいがく", romaji: "daigaku", es: "universidad" },
    { jp: "びょういん", romaji: "byouin", es: "hospital" },
    { jp: "でんき", romaji: "denki", es: "electricidad, luz eléctrica" },
    { jp: "だれ", romaji: "dare", es: "quién" },
    { jp: "どなた", romaji: "donata", es: "quién (forma cortés)" },
    { jp: "さい", romaji: "sai", es: "años de edad" },
    { jp: "なんさい", romaji: "nansai", es: "cuántos años" },
    { jp: "おいくつ", romaji: "oikutsu", es: "forma cortés de なんさい" },
    { jp: "はい", romaji: "hai", es: "sí" },
    { jp: "いいえ", romaji: "iie", es: "no" },
    { jp: "しつれいですが", romaji: "shitsurei desu ga", es: "disculpe, pero (pregunta personal)" },
    { jp: "おなまえは？", romaji: "onamae wa?", es: "¿Cuál es su nombre?" },
    { jp: "はじめまして", romaji: "hajimemashite", es: "mucho gusto (primera vez)" },
    { jp: "どうぞよろしく", romaji: "douzo yoroshiku", es: "encantado/a, mucho gusto" },
    { jp: "こちらは〜さんです", romaji: "kochira wa ~san desu", es: "Le presento al Sr./Sra./Srta. ~" },
    { jp: "〜からきました", romaji: "~kara kimashita", es: "Soy de ~ / Vengo de ~" },
    // Palabras opcionales - países y lugares
    { jp: "アメリカ", romaji: "amerika", es: "EE. UU.", optional: true },
    { jp: "イギリス", romaji: "igirisu", es: "Reino Unido", optional: true },
    { jp: "インド", romaji: "indo", es: "India", optional: true },
    { jp: "インドネシア", romaji: "indoneshia", es: "Indonesia", optional: true },
    { jp: "かんこく", romaji: "kankoku", es: "Corea del Sur", optional: true },
    { jp: "タイ", romaji: "tai", es: "Tailandia", optional: true },
    { jp: "ちゅうごく", romaji: "chuugoku", es: "China", optional: true },
    { jp: "ドイツ", romaji: "doitsu", es: "Alemania", optional: true },
    { jp: "にほん", romaji: "nihon", es: "Japón", optional: true },
    { jp: "フランス", romaji: "furansu", es: "Francia", optional: true },
    { jp: "ブラジル", romaji: "burajiru", es: "Brasil", optional: true },
    // Palabras opcionales - universidades ficticias
    { jp: "さくら大学", romaji: "sakura daigaku", es: "universidades ficticias", optional: true },
    { jp: "富士大学", romaji: "fuji daigaku", es: "universidades ficticias", optional: true },
    // Palabras opcionales - empresas ficticias
    { jp: "IMC", romaji: "IMC", es: "empresas ficticias", optional: true },
    { jp: "パワー電気", romaji: "pawaa denki", es: "empresas ficticias", optional: true },
    { jp: "ブラジルエアー", romaji: "burajiru eaa", es: "empresas ficticias", optional: true },
    { jp: "AKC", romaji: "AKC", es: "institución ficticia", optional: true },
    { jp: "神戸病院", romaji: "koube byouin", es: "hospital ficticio", optional: true }

  ],
  "Lección 2": [
    { jp: "これ", romaji: "kore", es: "éste, ésta, esto" },
    { jp: "それ", romaji: "sore", es: "ése, ésa, eso" },
    { jp: "あれ", romaji: "are", es: "aquél, aquélla, aquello" },
    { jp: "この〜", romaji: "kono~", es: "este~, esta~" },
    { jp: "その〜", romaji: "sono~", es: "ese~, esa~" },
    { jp: "あの〜", romaji: "ano~", es: "aquel~, aquella~" },
    { jp: "ほん", romaji: "hon", es: "libro" },
    { jp: "じしょ", romaji: "jisho", es: "diccionario" },
    { jp: "ざっし", romaji: "zasshi", es: "revista" },
    { jp: "しんぶん", romaji: "shinbun", es: "periódico" },
    { jp: "ノート", romaji: "nooto", es: "cuaderno" },
    { jp: "てちょう", romaji: "techou", es: "agenda" },
    { jp: "めいし", romaji: "meishi", es: "tarjeta de presentación" },
    { jp: "カード", romaji: "kaado", es: "tarjeta" },
    { jp: "テレホンカード", romaji: "terehonkaado", es: "tarjeta telefónica" },
    { jp: "えんぴつ", romaji: "enpitsu", es: "lápiz" },
    { jp: "ボールペン", romaji: "boorupen", es: "bolígrafo" },
    { jp: "シャープペンシル", romaji: "shaapupenshiru", es: "portaminas" },
    { jp: "かぎ", romaji: "kagi", es: "llave" },
    { jp: "とけい", romaji: "tokei", es: "reloj" },
    { jp: "かさ", romaji: "kasa", es: "paraguas" },
    { jp: "かばん", romaji: "kaban", es: "bolso, valija" },
    { jp: "テープ", romaji: "teepu", es: "cinta (cassette)" },
    { jp: "テープレコーダー", romaji: "teepu rekoodaa", es: "grabadora" },
    { jp: "テレビ", romaji: "terebi", es: "televisor" },
    { jp: "ラジオ", romaji: "rajio", es: "radio" },
    { jp: "カメラ", romaji: "kamera", es: "cámara" },
    { jp: "コンピューター", romaji: "konpyuutaa", es: "computadora" },
    { jp: "じどうしゃ", romaji: "jidousha", es: "automóvil" },
    { jp: "つくえ", romaji: "tsukue", es: "escritorio" },
    { jp: "いす", romaji: "isu", es: "silla" },
    { jp: "チョコレート", romaji: "chokoreeto", es: "chocolate" },
    { jp: "コーヒー", romaji: "koohii", es: "café" },
    { jp: "えいご", romaji: "eigo", es: "idioma inglés" },
    { jp: "にほんご", romaji: "nihongo", es: "idioma japonés" },
    { jp: "〜ご", romaji: "~go", es: "idioma ~" },
    { jp: "なん", romaji: "nan", es: "qué" },
    { jp: "そう", romaji: "sou", es: "así" },
    { jp: "ちがいます", romaji: "chigaimasu", es: "no, no es así" },
    { jp: "そうですか", romaji: "sou desu ka", es: "¿Ah sí?/¿Ya?" },
    { jp: "あのう", romaji: "anou", es: "esto..., bueno..." },
    { jp: "ほんのきもちです", romaji: "hon no kimochi desu", es: "es un obsequio modesto" },
    { jp: "どうぞ", romaji: "douzo", es: "por favor / aquí tiene" },
    { jp: "どうも", romaji: "doumo", es: "gracias" },
    { jp: "どうもありがとう", romaji: "doumo arigatou", es: "muchas gracias" },
    { jp: "これからおせわになります", romaji: "kore kara osewa ni narimasu", es: "le agradezco de antemano su apoyo" },
    { jp: "こちらこそよろしく", romaji: "kochira koso yoroshiku", es: "yo también encantado/a de conocerle" }
  ],
  "Lección 3": [
    { jp: "ここ", romaji: "koko", es: "aquí, este lugar" },
    { jp: "そこ", romaji: "soko", es: "ahí, ese lugar" },
    { jp: "あそこ", romaji: "asoko", es: "aquel lugar" },
    { jp: "どこ", romaji: "doko", es: "dónde" },
    { jp: "こちら", romaji: "kochira", es: "por aquí (forma cortés de ここ)" },
    { jp: "そちら", romaji: "sochira", es: "por ahí (forma cortés de そこ)" },
    { jp: "あちら", romaji: "achira", es: "por allí (forma cortés de あそこ)" },
    { jp: "どちら", romaji: "dochira", es: "por dónde (forma cortés de どこ)" },
    { jp: "きょうしつ", romaji: "kyoushitsu", es: "aula" },
    { jp: "しょくどう", romaji: "shokudou", es: "comedor" },
    { jp: "じむしょ", romaji: "jimusho", es: "oficina" },
    { jp: "かいぎしつ", romaji: "kaigishitsu", es: "sala de reuniones" },
    { jp: "うけつけ", romaji: "uketsuke", es: "recepción" },
    { jp: "ロビー", romaji: "robii", es: "lobby, vestíbulo" },
    { jp: "へや", romaji: "heya", es: "habitación, cuarto" },
    { jp: "トイレ", romaji: "toire", es: "baño" },
    { jp: "かいだん", romaji: "kaidan", es: "escaleras" },
    { jp: "エレベーター", romaji: "erebeetaa", es: "ascensor" },
    { jp: "エスカレーター", romaji: "esukareetaa", es: "escalera mecánica" },
    { jp: "おくに", romaji: "okuni", es: "su país, patria" },
    { jp: "かいしゃ", romaji: "kaisha", es: "empresa, compañía" },
    { jp: "うち", romaji: "uchi", es: "casa, hogar" },
    { jp: "でんわ", romaji: "denwa", es: "teléfono" },
    { jp: "くつ", romaji: "kutsu", es: "zapatos" },
    { jp: "ネクタイ", romaji: "nekutai", es: "corbata" },
    { jp: "ワイン", romaji: "wain", es: "vino" },
    { jp: "たばこ", romaji: "tabako", es: "tabaco, cigarrillos" },
    { jp: "うりば", romaji: "uriba", es: "sección (en grandes almacenes)" },
    { jp: "ちか", romaji: "chika", es: "sótano" },
    { jp: "〜かい", romaji: "~kai", es: "piso, planta" },
    { jp: "なんがい", romaji: "nangai", es: "qué piso" },
    { jp: "えん", romaji: "en", es: "yen (moneda)" },
    { jp: "いくら", romaji: "ikura", es: "cuánto (dinero)" },
    { jp: "ひゃく", romaji: "hyaku", es: "cien" },
    { jp: "せん", romaji: "sen", es: "mil" },
    { jp: "まん", romaji: "man", es: "diez mil" },
    { jp: "すみません", romaji: "sumimasen", es: "disculpe (llamar atención)" },
    { jp: "〜をみせてください", romaji: "~wo misete kudasai", es: "por favor, muéstreme [~]" },
    { jp: "じゃ", romaji: "ja", es: "entonces (al decidir o pedir algo)" },
    { jp: "〜をください", romaji: "~wo kudasai", es: "dame [~], por favor" },
    { jp: "しんおおさか", romaji: "shin oosaka", es: "Shin-Osaka (estación)" }
  ],
  "Lección 4": [
    { jp: "おきます", romaji: "okimasu", es: "levantarse" },
    { jp: "ねます", romaji: "nemasu", es: "acostarse, ir a la cama" },
    { jp: "はたらきます", romaji: "hatarakimasu", es: "trabajar" },
    { jp: "やすみます", romaji: "yasumimasu", es: "descansar, estar de vacaciones" },
    { jp: "べんきょうします", romaji: "benkyou shimasu", es: "estudiar" },
    { jp: "おわります", romaji: "owarimasu", es: "terminar" },
    { jp: "デパート", romaji: "depaato", es: "grandes almacenes, tienda departamento" },
    { jp: "ぎんこう", romaji: "ginkou", es: "banco (institución financiera)" },
    { jp: "ゆうびんきょく", romaji: "yuubinkyoku", es: "oficina de correos" },
    { jp: "としょかん", romaji: "toshokan", es: "biblioteca" },
    { jp: "びじゅつかん", romaji: "bijutsukan", es: "museo de arte" },
    { jp: "いま", romaji: "ima", es: "ahora" },
    { jp: "〜じ", romaji: "~ji", es: "las ~ horas" },
    { jp: "〜ふん", romaji: "~fun", es: "~ minutos" },
    { jp: "はん", romaji: "han", es: "y media (v.g. 6 じ はん las seis y media)" },
    { jp: "なんじ", romaji: "nanji", es: "¿qué hora?" },
    { jp: "なんぷん", romaji: "nanpun", es: "¿qué minuto?" },
    { jp: "ごぜん", romaji: "gozen", es: "de la mañana" },
    { jp: "ごご", romaji: "gogo", es: "de la tarde" },
    { jp: "あさ", romaji: "asa", es: "la mañana" },
    { jp: "ひる", romaji: "hiru", es: "día, mediodía" },
    { jp: "ばん", romaji: "ban", es: "noche" },
    { jp: "おととい", romaji: "ototoi", es: "anteayer" },
    { jp: "きのう", romaji: "kinou", es: "ayer" },
    { jp: "きょう", romaji: "kyou", es: "hoy" },
    { jp: "あした", romaji: "ashita", es: "mañana" },
    { jp: "あさって", romaji: "asatte", es: "pasado mañana" },
    { jp: "けさ", romaji: "kesa", es: "esta mañana" },
    { jp: "こんばん", romaji: "konban", es: "esta noche" },
    { jp: "やすみ", romaji: "yasumi", es: "descanso, día libre, feriado" },
    { jp: "ひるやすみ", romaji: "hiruyasumi", es: "descanso de mediodía" },
    { jp: "まいあさ", romaji: "maiasa", es: "todas las mañanas, cada mañana" },
    { jp: "まいばん", romaji: "maiban", es: "todas las noches, cada noche" },
    { jp: "まいにち", romaji: "mainichi", es: "todos los días, cada día" },
    { jp: "げつようび", romaji: "getsuyoubi", es: "lunes" },
    { jp: "かようび", romaji: "kayoubi", es: "martes" },
    { jp: "すいようび", romaji: "suiyoubi", es: "miércoles" },
    { jp: "もくようび", romaji: "mokuyoubi", es: "jueves" },
    { jp: "きんようび", romaji: "kinyoubi", es: "viernes" },
    { jp: "どようび", romaji: "doyoubi", es: "sábado" },
    { jp: "にちようび", romaji: "nichiyoubi", es: "domingo" },
    { jp: "なんようび", romaji: "nanyoubi", es: "qué día de la semana" },
    { jp: "ばんごう", romaji: "bangou", es: "número" },
    { jp: "なんばん", romaji: "nanban", es: "qué número" }
  ]
};

if (typeof window !== "undefined") window.vocabulario = vocabulario;
